"""add root_cause table

Revision ID: 95af6a5aa115
Revises: a555f4d491af
Create Date: 2021-12-20 16:43:37.001911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95af6a5aa115'
down_revision = 'a555f4d491af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bug', 'bug_tracker_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'bug', ['bug_tracker_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bug', type_='unique')
    op.alter_column('bug', 'bug_tracker_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
