"""add new table

Revision ID: 1533ef88481e
Revises: 
Create Date: 2021-12-21 23:31:55.502661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1533ef88481e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_tracker_url', sa.String(), nullable=True),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bug_tracker_url'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bug', schema='public')
    # ### end Alembic commands ###
